### ISSUE TITLE
implement switching outbound and inbound

### ISSUE THREAD

**Issue by knmcguire** [tudelft/SGBA_CF2_App_layer#5]
To truly be SGBA as in the paper, the app should switch to inbound if battery gets empty or if some time has passed by.

**Comment by Admire-ljb** [comment]
Hello, 
         whether the inbound mode has been written into the code? 
         Just the switch not have been implemented yet or?

**Comment by knmcguire** [comment]
nop! not implemented yet. But should not be difficult to do. It will need to be based on the pm.vbat log variable from the crazyflie.

**Comment by Admire-ljb** [comment]
Has the inbound mode been implemented in SGBA_code_SR_2019?

**Comment by knmcguire** [comment]
yes, it has been implemented in there, but ofcourse inbound will only work if therre is a connection with the beacon.
