### ISSUE TITLE
Error in LED driver while compiling

### ISSUE THREAD

**Issue by williamleong** [tudelft/SGBA_CF2_App_layer#8]
Hi @knmcguire, while following the instructions, @tamiewong and I encountered a problem during compilation:

````
crazyflie-firmware/src/drivers/src/ws2812_cf2.c: In function 'ws2812DmaIsr':
crazyflie-firmware/src/drivers/src/ws2812_cf2.c:219:16: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
  219 |       buffer = led_dma.begin;
      |                ^~~~~~~
crazyflie-firmware/src/drivers/src/ws2812_cf2.c:225:16: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
  225 |       buffer = led_dma.end;
      |                ^~~~~~~
cc1: all warnings being treated as errors
````

While we could remove `-Werror` from the Makefile, I wonder if there is some update to solve this problem. My compiler is arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release) from Ubuntu 22.04.

**Comment by knmcguire** [comment]
Sorry for the late reply! I hardly watch this repo as there is not much activity. but this seems to happen in the firmware and not the app layer part... Also I  this particular app layer hasn't been compiled with the latest version of the crazyflie firmware for a long time...

If you can post this on https://discussions.bitcraze.io/ you'll have more success to be honest. Also, I would advise to crossreference this with the [wall following example ](https://github.com/bitcraze/crazyflie-firmware/tree/master/examples/demos/app_wall_following_demo)in the crazyflie firmware repo, which is almost the same wall following code as this one. Then you can check out the changes that have been done lately to get the app layer example to work

**Comment by williamleong** [comment]
Thanks for getting back. We managed to get it to work by making some small changes and are also trying to see if it will work with the latest version of the crazyflie firmware.
